"""Stage 09 — chunk ablation behavior runs.

For each selected candidate × chunk:
  c_minus_j     = candidate.compressed_text with chunk j removed
  stress_minus_j = T^K(c_minus_j) under same ACON UTCO compressor
  behavior(T^K(c_minus_j)) — downstream AppWorld run

Also runs the unablated full context T^K(c) as control.

MUST be invoked from acon/.venv (uses AppWorld runner).
Output: outputs/raw/chunk_ablation_contexts.jsonl,
        outputs/raw/chunk_ablation_behavior_runs.jsonl
"""

from __future__ import annotations

import argparse
import json
import sys
import time
from concurrent.futures import ProcessPoolExecutor, as_completed
from pathlib import Path
from typing import Dict, List, Tuple

_REPO = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(_REPO))

# This script is invoked with acon/.venv. Two helpers run in subprocesses:
# 1) _stress_one — recompress (uses EASMO/.venv via direct module reference; must
#    avoid importing motivation_v9 package that bridges into v3/v2 which conflict with v1 pydantic).
#    Instead, we precompute all stressed contexts up-front in the main process
#    BEFORE spawning the AppWorld workers, so the AppWorld workers only need to
#    run the downstream agent and not touch the compressor at all.
# 2) _run_agent — runs the AppWorld agent (acon/.venv).


def _read(p):
    out = []
    with open(p) as f:
        for line in f:
            if line.strip():
                out.append(json.loads(line))
    return out


def _run_agent(args_tuple):
    sys.path.insert(0, str(_REPO))
    sys.path.insert(0, "/workspace/EASMO/motivation_v4")
    sys.path.insert(0, "/workspace/EASMO/motivation_v3")
    sys.path.insert(0, "/workspace/EASMO/motivation_v2")
    from motivation_v4.runner import run_with_compressed_context
    (ablation_id, candidate_id, chunk_id, case_id, ablation_type,
     text, max_steps, tag) = args_tuple
    res = run_with_compressed_context(
        task_id=case_id,
        method=f"v9_chunk_{ablation_type}",
        compressed_context=text,
        max_steps=max_steps,
        tag=tag,
    )
    return {
        "ablation_id":        ablation_id,
        "candidate_id":       candidate_id,
        "chunk_id":           chunk_id,
        "case_id":            case_id,
        "ablation_type":      ablation_type,
        "max_steps":          max_steps,
        "success":            res.success,
        "score":              res.final_reward,
        "iterations":         res.iterations,
        "termination_reason": res.termination_reason,
        "compressed_chars":   len(text),
        "compressed_tokens_est": max(1, len(text) // 4),
        "elapsed_s":          res.elapsed_s,
        "output_dir":         res.output_dir,
        "error":              res.error,
    }


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--chunks", default=str(_REPO / "outputs/raw/chunks.jsonl"))
    ap.add_argument("--candidates",
                    default=str(_REPO / "outputs/raw/candidate_compressions.jsonl"))
    ap.add_argument("--ablation_contexts",
                    default=str(_REPO / "outputs/raw/chunk_ablation_contexts.jsonl"))
    ap.add_argument("--out",
                    default=str(_REPO / "outputs/raw/chunk_ablation_behavior_runs.jsonl"))
    ap.add_argument("--budgets", nargs="+", type=int, default=[15])
    ap.add_argument("--workers", type=int, default=6)
    ap.add_argument("--tag", default="mv9_chunk")
    args = ap.parse_args()

    chunks = _read(args.chunks)
    candidates = _read(args.candidates)
    cand_idx = {c["candidate_id"]: c for c in candidates}

    # Read pre-built ablation contexts (must be generated by a separate
    # EASMO/.venv-side preprocessing step — see helper `09a_build_chunk_contexts.py`).
    if not Path(args.ablation_contexts).exists():
        print(f"[09] expected {args.ablation_contexts} — please run "
              f"`scripts/09a_build_chunk_contexts.py` first under EASMO/.venv.")
        return
    contexts = _read(args.ablation_contexts)
    print(f"[09] {len(contexts)} ablation contexts loaded")

    out_path = Path(args.out)
    out_path.parent.mkdir(parents=True, exist_ok=True)
    done_ids = set()
    if out_path.exists():
        for r in _read(out_path):
            done_ids.add(r.get("ablation_id"))
    print(f"[09] {len(done_ids)} ablation runs already done")

    work: List[Tuple] = []
    for ctx in contexts:
        if ctx["ablation_id"] in done_ids:
            continue
        text = ctx.get("post_stress_text") or ctx.get("pre_stress_text") or ""
        if not text:
            continue
        for cap in args.budgets:
            wid = f"{ctx['ablation_id']}__cap{cap}"
            work.append((
                wid, ctx["candidate_id"], ctx.get("chunk_id"), ctx["case_id"],
                ctx["ablation_type"], text, cap, args.tag,
            ))

    print(f"[09] {len(work)} agent runs pending; workers={args.workers}")

    t0 = time.time()
    n_done = 0; n_err = 0; n_pass = 0
    with open(out_path, "a", encoding="utf-8") as f_out:
        with ProcessPoolExecutor(max_workers=args.workers) as ex:
            futs = {ex.submit(_run_agent, w): w for w in work}
            for fut in as_completed(futs):
                try:
                    rec = fut.result()
                except Exception as e:
                    rec = {"error": str(e)}
                if rec.get("error"):
                    n_err += 1
                if rec.get("success"):
                    n_pass += 1
                f_out.write(json.dumps(rec, ensure_ascii=False) + "\n")
                f_out.flush()
                n_done += 1
                if n_done % 10 == 0 or n_done <= 3:
                    eta = (time.time() - t0) / n_done * (len(work) - n_done)
                    print(f"  [{n_done:>4d}/{len(work)}] pass={n_pass:<3d} err={n_err:<3d} eta={eta:.0f}s",
                          flush=True)
    print(f"[09] done: {n_done} ablation runs ({n_pass} success, {n_err} errors)")


if __name__ == "__main__":
    main()
